home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
]

ozan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews
from user import views as userviews

urlpatterns = [
    path('', include('home.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
    path('restaurant/', include('restaurant.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('restaurant/<int:id>/', views.restaurants_detail, name='restaurants_detail'),
    path('search/',views.food_search, name='food_search'),
    path('search_auto/',views.food_search_auto, name='food_search_auto'),
    path('logout/',views.logout_view,name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('join/', views.join_view, name='join_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('category/<int:id>/<slug:slug>/', views.category_restaurants, name='category_restaurants'),
    path('user_profile/',userviews.index, name='index'),
    path('faq/',views.faq, name='faq')

]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /restaurant/
    path('', views.index, name='index'),
    path('addcomment/<int:id>',views.addcomment,name='addcomment')
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    adress = models.CharField(blank=True,max_length=150)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    smtpserver = models.CharField(blank=True,max_length=20)
    smtpemail = models.CharField(blank=True,max_length=50)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=255)
    aboutus = RichTextUploadingField(blank=True)
    contact =RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New','New'),
        ('Read','Read'),
        ('Closed','Closed'),
    )
    name= models.CharField(blank=True,max_length=20)
    email= models.CharField(blank=True,max_length=50)
    subject= models.CharField(blank=True,max_length=50)
    message= models.CharField(blank=True,max_length=255)
    status= models.CharField(max_length=10,choices=STATUS,default='New')
    ip= models.CharField(blank=True,max_length=20)
    note= models.CharField(blank=True,max_length=100)
    create_at= models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name'   : TextInput(attrs={'class':'form-control valid','placeholder':'Name-Surname'}),
            'subject': TextInput(attrs={'class': 'form-control valid', 'placeholder': 'Subject'}),
            'email'  : TextInput(attrs={'class': 'form-control valid', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'form-control w-100', 'placeholder': 'Your Message'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    image = models.ImageField(blank=True,upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '['+ self.user.username + '] ' + self.user.first_name+ ' ' + self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone','address','image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.question

restaurant/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    image = models.ImageField(blank=True,upload_to='images/')
    status = models.CharField(max_length=10,choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self',blank=True,null=True,related_name='children',on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k=self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' >> '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('category_detail',kwargs={'slug':self.slug})

class Restaurant(models.Model):
    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    detail =RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Foods(models.Model):
    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    price = models.FloatField()
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Images(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True','Evet'),
        ('False','Hayır'),
    )
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=50,blank=True)
    comment = models.TextField(max_length=200,blank=True)
    rate = models.IntegerField(blank=True)
    status= models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True,max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject','comment','rate']

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.forms import SearchForm, JoinForm
from home.models import Setting, ContactForm, ContactFormMessage, FAQ, UserProfile
from order.models import ShopCart
from restaurant.models import Foods, Category, Restaurant, Images, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Foods.objects.all().order_by('-id')[:5]
    category = Category.objects.all()
    lastrestaurants = Restaurant.objects.all().order_by('-id')[:6]
    current_user = request.user
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # count item in shopcart

    context = {'setting': setting,
               'category': category,
               'page': 'home',
               'sliderdata': sliderdata,
               'lastrestaurants': lastrestaurants}
    return render(request, 'index.html', context)


def restaurants(request):
    restaurant = Restaurant.objects.all()
    category = Category.objects.all()
    context = {'restaurant': restaurant,'category':category}
    return render(request, 'restaurants.html', context)

def category_restaurants(request,id,slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    restaurant = Restaurant.objects.filter(category_id=id)
    context ={'category':category,'restaurant':restaurant,'categorydata':categorydata}
    return render(request,'restaurants.html',context)


def aboutus(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    context = {'setting': setting, 'page': 'aboutus','category':category}
    return render(request, 'aboutus.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactFormMessage()
            data.name = form.cleaned_data['name']  # formdan bilgiyi al
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()  # veri tabanına kaydet
            messages.success(request, "Mesajınız başarı ile gönderilmiştir.Teşekkür ederiz.")
            return HttpResponseRedirect('/contact')

    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    form = ContactForm()
    context = {'setting': setting, 'form': form,'category':category}
    return render(request, 'contact.html', context)

def restaurants_detail(request, id):
    restaurant = Restaurant.objects.get(pk=id)
    images = Images.objects.filter(restaurant_id=id)
    foods = Foods.objects.filter(restaurant_id=id)
    comments = Comment.objects.filter(restaurant_id=id,status='True')
    category = Category.objects.all()
    context = {'restaurant': restaurant, 'images': images, 'foods': foods,'comments':comments,'category':category}
    return render(request, 'restaurants_detail.html', context)

def food_search(request):
    if request.method == 'POST': #form post edildiyse
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query'] #formdan bilgiyi al
            foods = Foods.objects.filter(title__icontains=query) #Select * from food where title like %query%
            restaurant = Restaurant.objects.all()[:1]
            #return HtttpResponse(foods)
            context = {'foods':foods,
                       'category':category,
                       'restaurant':restaurant}
            return render(request,'foods_search.html',context)
    return HttpResponseRedirect('/')

def food_search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        food = Foods.objects.filter(city__icontains=q)
        results = []
        for rs in food:
            food_json = {}
            food_json = rs.title
            results.append(food_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Login Hatası ! Kullanıcı adı yada şifre hatalı.")
            return HttpResponseRedirect('/login')
    category = Category.objects.all()
    context = {'category': category}
    return render(request,'login.html', context )

def join_view(request):
    if request.method == 'POST':
        form = JoinForm(request.POST)
        if form.is_valid():
            form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username,password=password)
        login(request,user)
        #Create data in profile for user
        current_user=request.user
        data = UserProfile()
        data.user_id =current_user.id
        data.image = "images/users/user.png"
        data.save()
        return HttpResponseRedirect('/')
    category = Category.objects.all()
    form = JoinForm()
    context = {'form':form,'category': category}
    return render(request, 'join.html',context)


def faq(request):
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('ordernumber')
    context = {
        'category': category,
        'faq':faq
    }
    return render(request, 'faq.html', context)

restaurant/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from restaurant.models import CommentForm, Comment


def index(request):
    return HttpResponse("Restaurant Page")

@login_required(login_url='login') #login check
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    if request.method == 'POST': #form post edildiyse
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user=request.user #Acces User Session information
            data=Comment() #model ile bağlantı kur
            data.user_id = current_user.id
            data.restaurant_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save() # kaydet
            messages.success(request,"Yorumunuz başarı ile gönderilmiştir.Teşekkür ederiz")
            return HttpResponseRedirect(url) #kaydedildi
    messages.error(request, "Yorumunuz Kaydedilemedi! Lütfen kontrol ediniz.")
    return HttpResponseRedirect(url) #kaydedildi

home/templates/aboutus.html
{% extends "homebase.html" %}

{% block title %}AboutUs-{{setting.title}}{% endblock %}
{% block keywords %}{{setting.keywords}}{% endblock %}
{% block description %}{{setting.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <style>
    .banner-bg-1{
        background-image: url("../../uploads/images/banner.jpg");
    }
    </style>
     <!-- breadcrumb-start -->
    <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-1">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Our Company</h2>
                            <p> <a href="/">Home ></a> <span></span>AboutUs</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb-end -->
    <!-- about start -->
    <div class="about-area section-padding">
        <div class="container">
            <div class="row align-items-center">
                {{ setting.aboutus|safe}}
            </div>
        </div>
    </div>
    <!-- about end -->

{% endblock %}

home/templates/contact.html
{% extends "homebase.html" %}

{% block title %}Contact-{{setting.title}}{% endblock %}
{% block keywords %}{{setting.keywords}}{% endblock %}
{% block description %}{{setting.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <style>
    .banner-bg-1{
        background-image: url("../../uploads/images/banner.jpg");
    }
    </style>
    <!-- breadcrumb-start -->
    <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-1">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Contact Us</h2>
                            <p> <a href="/">Home ></a> <span></span>Contact</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb-end -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section">
        <div class="container">
            <div class="d-none d-sm-block mb-5 pb-4">
                <div class="row">
                    <div class="col-12">
                        <h2 class="contact-title">Contact Form</h2>
                    </div>
                    <div class="col-lg-6">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tag }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form  class="form-contact contact_form" method="post">
                            <div class="form-group">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="button button-contactForm boxed-btn">Send Message</button>
                            </div>
                        </form>

                    </div>
                    <div class="col-lg-6">
                        {{ setting.contact|safe}}
                    </div>
                </div>
            </div>
    </section>
    <!-- ================ contact section end ================= -->

{% endblock %}

home/templates/restaurants_detail.html
{% extends "homebase.html" %}

{% block title %}{{ restaurant.title }}{% endblock %}
{% block keywords %}{{restaurant.keywords}}{% endblock %}
{% block description %}{{restaurant.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <style>

        .shop-detail-box-main{
            padding: 70px 0px;
        }
        .single-product-slider .carousel-control-prev {
            bottom: auto;
            background: #111111;
            width: 6%;
            padding: 10px 0;
            background-image: none;
            top: 40%;
        }
        .single-product-slider .carousel-control-next {
            bottom: auto;
            background: #111111;
            width: 6%;
            padding: 10px 0;
            background-image: none;
            top: 40%;
        }
        .single-product-slider .carousel-indicators li img {
            opacity: 0.5;
        }
        .single-product-slider .carousel-indicators li.active img {
            opacity: 1;
        }
        .carousel-indicators{
            position: relative;
            bottom: 0;
            background: #000000;
        }
        .carousel-indicators li{
            width: 30%;
            height: 100%;
            cursor: pointer;
        }
        .single-product-details h2{
            color: #000000;
            font-weight: 700;
            font-size: 24px;
        }
        .single-product-details h5 {
            color: #b0b435;
            font-weight: 700;
            font-size: 18px;
        }
        .single-product-details h5 del {
            font-size: 13px;
            color: #666;
        }
        .available-stock span {
            font-size: 15px;
        }
        .available-stock span a {
            color: #b0b435;
        }
        .single-product-details h4{
            font-size: 18px;
            font-weight: 700;
            margin-top: 20px;
        }
        .single-product-details p{
            font-size: 16px;
            margin-bottom: 20px;
        }
        .single-product-details ul{
            display: inline-block;
            width: 100%;
            border: 1px #000000 dashed;
            margin-bottom: 30px;
        }
        .single-product-details ul li{
            width: 50%;
            float: left;
            padding: 0px 15px;
        }
        .size-st .bootstrap-select > .dropdown-toggle.btn-light{
            background: #000000;
            border: none;
            border-radius: 0px;
            color: #ffffff;
        }
        .quantity-box input{
            width: 100%;
        }
        .price-box-bar{
            margin-bottom: 30px;
        }
        .price-box-bar a{
            padding: 10px 20px;
            font-weight: 700;
            color: #ffffff;
            border: none;
        }
        .add-to-btn .add-comp {
            float: left;
        }
        .add-to-btn .share-bar {
            float: right;
        }
        .add-comp a{
            padding: 10px 20px;
            font-weight: 700;
            color: #ffffff;
            border: none;
        }
        .share-bar{
        }
        .share-bar a {
            background: #b0b435;
            color: #ffffff;
            padding: 5px 10px;
            display: inline-block;
            width: 34px;
            text-align: center;
        }
        .share-bar a {
        }
        .banner-bg-1{
            background-image: url("../../uploads/images/banner.jpg");
        }

    </style>
    <!-- breadcrumb-start -->
    <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-1">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Our Restaurants</h2>
                            <p> <a href="/">Home ></a> <span></span>{{ restaurant.title }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb-end -->
    <div class="shop-detail-box-main">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-6">
                    <div class="slider-area" style="height: 250px">
                        <div class="slider-active owl-carousel">
                            {% for rs in images %}
                                <div class="single-slider " style="height: 300px">
                                    <img class="overlay-image" src="{{ rs.image.url }}" alt="">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-6">
                    <div class="single-product-details">
                        <h2>{{ restaurant.title }}</h2>
                        <h4>Restaurants Info:</h4>
                        <p>{{ restaurant.detail|safe}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="container">
        {% for rs in foods %}
            <div class="card mb-3" style="max-width: 100%;" >
                <div class="row no-gutters" >
                    <div class="col-md-4">
                        <img style="height: 140px" class="d-block w-100" src="{{ rs.image.url }}" alt="First slide">
                    </div>
                    <div class="col-md-4">
                        <div class="card-body">
                            <h3 class="card-title">{{ rs.title }}</h3>
                            <h4><b>Price</b></h4>
                            <p><strong>{{ rs.price }}₺</strong></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card-body">
                            <form action="/order/addtocart/{{ rs.id }}" method="post">
                                {% csrf_token %}
                                <h4><b>Quantity</b></h4>
                                <input name="quantity" value="1" min="1" type="number"  required data-error="Please enter Quantity">
                                <input type="submit" value="Add Cart" class="btn btn-success btn-group-lg">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="container">
        <div class="card card-outline-secondary my-4">
            <div class="card-header">
                <h2>Comments</h2>
            </div>
            <div class="card-body">
                <div class="media mb-3">
                    <div class="media-body">
                        {% for rs in comments %}
                            <h4>{{ rs.subject }} [Rate:{{ rs.rate }}]</h4>
                            <p>
                                {{ rs.comment }}
                            </p>
                            <hr>
                        {% endfor %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tag }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <h1>Write Your Comment</h1>
                        <form action="/restaurant/addcomment/{{ restaurant.id }}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <select class="form-control" name="rate">
                                            <option>Rate</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                            <option>5</option>
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="id_subject" name="subject" placeholder="Subject" required data-error="Please enter your Subject">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <textarea class="form-control" id="id_comment" name="comment" placeholder="Your Comment" rows="4" data-error="Write your message" required></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="submit-button text-center">
                                        {% if user.id is not None %}
                                            <button class="btn btn-success" type="submit">Send Comment</button>
                                        {% else %}
                                            Yorum eklemek için login olunuz!
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}