home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
]

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /restaurant/
    path('', views.index, name='index'),
    path('addtocart/<int:id>',views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>',views.deletefromcart, name='deletefromcart'),
    path('orderproduct/',views.orderproduct, name='orderproduct'),

    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
]

ozan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews
from user import views as userviews

urlpatterns = [
    path('', include('home.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
    path('restaurant/', include('restaurant.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('restaurant/<int:id>/', views.restaurants_detail, name='restaurants_detail'),
    path('search/',views.food_search, name='food_search'),
    path('search_auto/',views.food_search_auto, name='food_search_auto'),
    path('logout/',views.logout_view,name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('join/', views.join_view, name='join_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('category/<int:id>/<slug:slug>/', views.category_restaurants, name='category_restaurants'),
    path('user_profile/',userviews.index, name='index'),
    path('faq/',views.faq, name='faq')

]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from restaurant.models import Restaurant, Foods


class ShopCart(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    restaurant = models.ForeignKey(Restaurant,on_delete=models.SET_NULL,null=True)
    food = models.ForeignKey(Foods,on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.food
    @property
    def amount(self):
        return (self.quantity * self.food.price)
    @property
    def price(self):
        return (self.food.price)

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Preaparing','Preaparing'),
        ('OnRoad','OnRoad'),
        ('Completed','Completed'),
        ('Canceled', 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5,editable=False)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20,blank=True)
    address = models.CharField(max_length=20, blank=True)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True,max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields =['first_name','last_name','address','phone']

class OrderProduct(models.Model):
    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Canceled','Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    foods = models.ForeignKey(Foods, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.foods.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from home.models import UserProfile
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderProduct
from restaurant.models import Category, Foods


def index(request):
    return HttpResponse("Order App")

@login_required(login_url='/login') #check login
def addtocart(request,id):
    url = request.META.get('HTTP_REFERER') #get last url
    current_user = request.user  # accsess user session info

    check = ShopCart.objects.filter(food_id=id) #ürün sepette varmı
    if check:
        control = 1 #ürün sepette var
    else:
        control = 0 #ürün sepette yok
    if request.method == 'POST': #method post edildiyse
        form = ShopCartForm(request.POST)
        if form.is_valid():

            if control == 1: #ürün varsa güncelle
                data = ShopCart.objects.get(food_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save() #DB kaydet
            else :
                data = ShopCart() #model ile bağlantı kur
                data.user_id = current_user.id
                data.food_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save() # DB kaydet
            request.session['cart_items']=ShopCart.objects.filter(user_id=current_user.id).count() #count item in shopcart

            return HttpResponseRedirect(url)

    messages.warning(request,"Ürün eklemede hata oluştu!!.Lütfen Kontrol ediniz.")
    return HttpResponseRedirect(url)

@login_required(login_url='/login')
def shopcart(request):
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    category = Category.objects.all()
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # count item in shopcart
    total = 0
    for rs in shopcart:
        total += rs.food.price * rs.quantity

    context = {'shopcart': shopcart,
               'total':total,'category':category}

    return render(request,'Shopcart_food.html',context)

@login_required(login_url='/login') #check login
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    current_user = request.user
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # count item in shopcart
    messages.success(request,"Ürün Sepetten Silinmiştir.")
    return HttpResponseRedirect("/shopcart")


@login_required(login_url='/login') #check login
def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    scart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in scart:
        total += rs.food.price * rs.quantity

    if request.method == 'POST': #if there is a post
        form = OrderForm(request.POST)

        if form.is_valid():
            data =Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            #Move shopcart items to order products items
            scart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in scart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.restaurant_id = rs.food.restaurant_id
                detail.foods_id = rs.food_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price  = rs.food.price
                detail.amount = rs.amount
                detail.save()

            ShopCart.objects.filter(user_id=current_user.id).delete() #clear shopcart
            request.session['cart_items']=0
            return render(request,'Order_Completed.html',{'ordercode':ordercode,'category':category})

        else:
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
        'scart':scart,
        'category':category,
        'total':total,
        'form':form,
        'profile':profile
    }
    return render(request,'Order_Form.html',context)

order/templates/Order_Completed.html
{% extends "homebase.html" %}

{% block title %}Completed-{{setting.title}}{% endblock %}
{% block keywords %}{{setting.keywords}}{% endblock %}
{% block description %}{{setting.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <!-- breadcrumb-start -->

    <!-- ================ contact section start ================= -->
    <section class="contact-section">
        <div class="container">
            <i class="fa fa-check-circle fa-5x">Siparişiniz bize ulaşmıştır.<br> Sipariş Kodunuz: {{ ordercode }} </i>


        </div>

    </section>
    <!-- ================ contact section end ================= -->

{% endblock %}

order/templates/Order_Form.html
{% extends "homebase.html" %}

{% block title %}Orders{{setting.title}}{% endblock %}
{% block keywords %}{{setting.keywords}}{% endblock %}
{% block description %}{{setting.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <style>
    .banner-bg-1{
        background-image: url("../../uploads/images/details-banner.jpg");
    }
    </style>
    <!-- breadcrumb-start -->
    <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-1">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>OrderForm</h2>
                            <p> <a href="/">Home ></a> <span></span>OrderForm</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb-end -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section">
        <div class="container">
            <div class="d-none d-sm-block mb-5 pb-4">
                <div class="row">
                    <div class="col-12">
                        <h2 class="contact-title">Contact Form</h2>
                    </div>
                    <div class="col-lg-6">
                        <form  class="form-contact contact_form" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <p><label for="id_first_name">Name:</label>
                                    <input type="text" name="first_name" value="{{ user.first_name }}" class="form-control valid" placeholder="Name"></p>
                                <p><label for="id_last_name">Surname</label>
                                    <input type="text" name="last_name" value="{{ user.last_name }}" class="form-control valid" placeholder="Surname"></p>
                                <p><label for="id_address">Address</label>
                                    <input type="text" name="address" value="{{ profile.address }}" class="form-control valid" placeholder="Address"></p>
                                <p><label for="id_phone">Phone</label>
                                    <input type="text" name="phone" value="{{ profile.phone }}" class="form-control valid" placeholder="phone"></p>
                                <button type="submit" class="button button-contactForm boxed-btn">Completed Order</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-6">
                        <p><label for="id_first_name">Total:</label>
                            <input type="text"  class="form-control valid" readonly value="${{ total }}" ></p>
                        <p><label for="id_first_name">Credit Card Holder:</label>
                            <input type="text"   class="form-control valid" ></p>
                        <p><label for="id_last_name">Credit Card Number</label>
                            <input type="text"   class="form-control valid" ></p>
                        <p><label for="id_address">Credit Exp Date/year</label>
                            <input type="text"   class="form-control valid" placeholder="MM/YY"></p>
                        <p><label for="id_phone">Security Number</label>
                            <input type="text"   class="form-control valid" ></p>
                    </div>
                </div>
                <div class="row">
                    <table cellpadding="3" width="1200"  class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th></th>
                            <th>Restaurant</th>
                            <th>Food Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for rs in scart %}
                            <tr>
                                <td> <img src="{{ rs.food.image.url }}" style="height: 50px;"></td>
                                <td><h4>{{ rs.food.restaurant }}</h4></td>
                                <td><h4>{{ rs.food }}</h4></td>
                                <td><h4>${{ rs.food.price }}</h4></td>
                                <td><h4>{{ rs.quantity }}</h4></td>
                                <td><h4>${{ rs.amount }}</h4></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
    </section>
    <!-- ================ contact section end ================= -->

{% endblock %}

order/templates/Shopcart_food.html
{% extends "homebase.html" %}

{% block title %}ShopCart{% endblock %}
{% block keywords %}{{setting.keywords}}{% endblock %}
{% block description %}{{setting.description}}{% endblock %}

{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}' />{% endblock %}

{% block content %}
    <style>
    .banner-bg-1{
        background-image: url("../../uploads/images/banner.jpg");
    }
    </style>
    <!-- breadcrumb-start -->
    <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-1">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>ShopCart</h2>
                            <p> <a href="/">Home ></a> <span></span>ShopCart</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb-end -->
    <div class="service-area">
        <div class="container">
            <div class="row">
                <table cellpadding="3" width="1200"  class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th></th>
                        <th>Restaurant</th>
                        <th>Food Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rs in shopcart %}
                        <tr>
                            <td> <img src="{{ rs.food.image.url }}" style="height: 50px;"></td>
                            <td><h4>{{ rs.food.restaurant }}</h4></td>
                            <td><h4>{{ rs.food }}</h4></td>
                            <td><h4>${{ rs.food.price }}</h4></td>
                            <td><h4>{{ rs.quantity }}</h4></td>
                            <td><h4>${{ rs.amount }}</h4></td>
                            <td><a href="/order/deletefromcart/{{ rs.id}}" class="btn-sm btn-danger" onclick="return confirm('Are you sure?')">X</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <th colspan="4"></th>
                        <th>TOTAL</th>
                        <th colspan="2">${{ total }}</th>
                    </tr>
                    <tr>
                        <th colspan="4"></th>
                        <th><a href="/order/orderproduct" class="btn btn-block btn-success">SatınAl</a></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}